from django.contrib import admin
from .models import *

admin.site.register(Plant)
admin.site.register(Plantstage)
admin.site.register(Plantstagelog)
admin.site.register(Strain)
admin.site.register(Breeder)
admin.site.register(Mediumtype)
admin.site.register(Medium)
admin.site.register(Plantphoto)
admin.site.register(Grow)
admin.site.register(Growtype)
admin.site.register(Environment)
admin.site.register(Measurement)
admin.site.register(Unit)
admin.site.register(Unittype)
admin.site.register(Actioncategory)
admin.site.register(Actiontype)
admin.site.register(ActionLog)
admin.site.register(Nutrient)
admin.site.register(Nutrition)
admin.site.register(Group)
admin.site.register(Measurementtype)
