from django.urls import path

from . import views

urlpatterns = [
    path("plants/", views.plants, name="plants"),
    path("plant/<int:plant_id>/", views.plant, name="plant"),
    path("grows/", views.grows, name="grows"),
    path("grow/<int:grow_id>/", views.grow, name="grow"),
    path("environments/", views.environments, name="environments"),
    path("environment/<int:environment_id>/", views.environment, name="environment"),
    path("groups/", views.groups, name="groups"),
    path("group/<int:group_id>/", views.group, name="group"),
    path("plantstages/", views.plantstages, name="plantstages"),
    path("plantstage/<int:plantstage_id>/", views.plantstage, name="plantstage"),
    path("plantstagelogs/", views.plantstagelogs, name="plantstagelogs"),
    path("plantstagelog/<int:plantstagelog_id>/", views.plantstagelog, name="plantstagelog"),
    path("strains/", views.strains, name="strains"),
    path("strain/<int:strain_id>/", views.strain, name="strain"),
    path("breeders/", views.breeders, name="breeders"),
    path("breeder/<int:breeder_id>/", views.breeder, name="breeder"),
    path("mediumtypes/", views.mediumtypes, name="mediumtypes"),
    path("mediumtype/<int:mediumtype_id>/", views.mediumtype, name="mediumtype"),
    path("media/", views.media, name="media"),
    path("medium/<int:medium_id>/", views.medium, name="medium"),
    path("plantphotos/", views.plantphotos, name="plantphotos"),
    path("plantphoto/<int:plantphoto_id>/", views.plantphoto, name="plantphoto"),
    path("growtypes/", views.growtypes, name="growtypes"),
    path("growtype/<int:growtype_id>/", views.growtype, name="growtype"),
    path("environments_list/", views.environments_list, name="environments_list"),
    path("environment_detail/<int:environment_id>/", views.environment_detail, name="environment_detail"),
    path("measurements/", views.measurements, name="measurements"),
    path("measurement/<int:measurement_id>/", views.measurement, name="measurement"),
    path("units/", views.units, name="units"),
    path("unit/<int:unit_id>/", views.unit, name="unit"),
    path("unittypes/", views.unittypes, name="unittypes"),
    path("unittype/<int:unittype_id>/", views.unittype, name="unittype"),
    path("actioncategories/", views.actioncategories, name="actioncategories"),
    path("actioncategory/<int:actioncategory_id>/", views.actioncategory, name="actioncategory"),
    path("actiontypes/", views.actiontypes, name="actiontypes"),
    path("actiontype/<int:actiontype_id>/", views.actiontype, name="actiontype"),
    path("actionlogs/", views.actionlogs, name="actionlogs"),
    path("actionlog/<int:actionlog_id>/", views.actionlog, name="actionlog"),
    path("nutrients/", views.nutrients, name="nutrients"),
    path("nutrient/<int:nutrient_id>/", views.nutrient, name="nutrient"),
    path("nutritions/", views.nutritions, name="nutritions"),
    path("nutrition/<int:nutrition_id>/", views.nutrition, name="nutrition"),
    path("measurementtypes/", views.measurementtypes, name="measurementtypes"),
    path("measurementtype/<int:measurementtype_id>/", views.measurementtype, name="measurementtype"),
]
