# Generated by Django 4.2.23 on 2025-06-28 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='plants.plant'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement', to='grows.unit'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growtype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growtypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grow',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grows.growtype'),
        ),
        migrations.AddField(
            model_name='grow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouptype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grouptypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='grow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='grows.grow'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_types', to='grows.actioncategory'),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actiontypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='Actioncategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='grows.actioncategory'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='action_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='grows.actiontype'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='grows.environment'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='grow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='grows.grow'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='plants.plant'),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actioncategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actioncategories', to=settings.AUTH_USER_MODEL),
        ),
    ]
