# Generated by Django 4.2.23 on 2025-06-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='grows.grow'),
        ),
    ]
