# Generated by Django 4.2.23 on 2025-06-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0003_alter_group_grow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grouptype',
        ),
    ]
