# Generated by Django 4.2.23 on 2025-06-28 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grows', '0005_remove_group_grow_alter_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement', to='grows.unit'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Measurementtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unittype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grows.unittype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurementtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='grows.measurementtype'),
        ),
    ]
