# Generated by Django 4.2.23 on 2025-06-30 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0002_alter_nutrition_actionlog_alter_nutrition_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantstage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantstages', to=settings.AUTH_USER_MODEL),
        ),
    ]
