# Generated by Django 4.2.23 on 2025-06-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_plant_type_delete_planttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_profiles/'),
        ),
    ]
